FROM python:3.9-slim

WORKDIR /app

# Copy only what's needed for tests
COPY requirements.test.txt .
COPY test/ ./test/
COPY optimisation/ ./optimisation/

# Install test dependencies
RUN pip install --no-cache-dir -r requirements.test.txt

# Run tests
CMD ["python", "-m", "unittest", "discover", "test/"]